insert into comment (id, post_id, user_id, msg) values (1, 48, 25, 'Cheetah');
insert into comment (id, post_id, user_id, msg) values (2, 16, 38, 'Western grey kangaroo');
insert into comment (id, post_id, user_id, msg) values (3, 25, 15, 'Stork, openbill');
insert into comment (id, post_id, user_id, msg) values (4, 12, 29, 'Red-capped cardinal');
insert into comment (id, post_id, user_id, msg) values (5, 46, 9, 'Shrew, mandras tree');
insert into comment (id, post_id, user_id, msg) values (6, 44, 22, 'Deer, swamp');
insert into comment (id, post_id, user_id, msg) values (7, 23, 44, 'Comb duck');
insert into comment (id, post_id, user_id, msg) values (8, 45, 25, 'Northern phalarope');
insert into comment (id, post_id, user_id, msg) values (9, 50, 32, 'Tern, royal');
insert into comment (id, post_id, user_id, msg) values (10, 32, 27, 'Harbor seal');
insert into comment (id, post_id, user_id, msg) values (11, 27, 10, 'Eagle, long-crested hawk');
insert into comment (id, post_id, user_id, msg) values (12, 39, 36, 'Wattled crane');
insert into comment (id, post_id, user_id, msg) values (13, 35, 39, 'Badger, honey');
insert into comment (id, post_id, user_id, msg) values (14, 17, 33, 'Boa, mexican');
insert into comment (id, post_id, user_id, msg) values (15, 47, 26, 'Bleeding heart monkey');
insert into comment (id, post_id, user_id, msg) values (16, 14, 14, 'Marine iguana');
insert into comment (id, post_id, user_id, msg) values (17, 25, 44, 'Skimmer, four-spotted');
insert into comment (id, post_id, user_id, msg) values (18, 14, 11, 'Nile crocodile');
insert into comment (id, post_id, user_id, msg) values (19, 6, 35, 'Giant otter');
insert into comment (id, post_id, user_id, msg) values (20, 28, 33, 'White-mantled colobus');